### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by atomGit** [SparkyBluefang/S4E#40] opened 2016-09-25 23:19 UTC
when clicking the S4E 'preferences' button in the add-on panel...

`XML Parsing Error: undefined entity
Location: chrome://status4evar/content/prefs.xul
Line Number 424, Column 8:							<button id="warningButton" command="status4evar-command-advanced-continue" label="&aboutWarningButton.label;" />
--------------------------------------------------------^`

FF 49 on Linux
S4E 2015.11.16.23.1-signed.1-let-fixed

not an issue in v2016.07.16.21b

**Comment by jputting** [comment] 2016-09-29 17:28
Hi,
I also had this issue with Status-4-Evar and managed to solve this issue by using the Development Channel Version 2016.07.16.21b: you can find it on the Firefox Add-on page for this add at the bottom of the page.

**Comment by argcargv** [comment] 2016-10-06 07:26
same here.
I think I am the only one with this problem 😐

**Comment by SparkyBluefang** [comment] 2016-10-12 23:47
Duplicate of #39

**Closed by SparkyBluefang** 2016-10-12 23:47 UTC
